services:
  db:
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYDQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
