services:
  db:
    image: postgres:alpine
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASS}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
