services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=uoc-blog
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
